---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: nginx-ingress
  namespace: flagger-system
spec:
  interval: 24h0m0s
  url: https://kubernetes.github.io/ingress-nginx

